In [5]:
def magic_seek(cluster_id, metadata):
    skip_rows = np.sum(metadata[:cluster_id])
    max_rows = metadata[cluster_id]
    return skip_rows, max_rows

In [7]:
# test = np.empty((0,2))
# test = np.concatenate(np.array([[1,2]]))
# test

result = np.array([])
result = np.append(result, np.array([1, 2]))

print(result)

[1. 2.]


In [8]:
data = np.random.random((20, 8))
train(data,4)

In [9]:
D, M, nbits = 8, 4, 2
index_pq = IndexPQ(D, M, nbits)

data = np.random.random((50, D))

index_ivfpq = IVF_PQ(nprob=2, nbits=4, D=D ,pq_index=index_pq)

index_ivfpq.train(data)
index_ivfpq.save('index_pq_ivf')
#===================================================================       

In [10]:
np.random.seed(42)
index_ivfpq.load('index_pq_ivf')
q = np.random.random(D)
index_ivfpq.search(q, 5)


[0 9]


array([30, 42, 35,  6,  1])

In [7]:
import numpy as np
arr = np.array([5, 1, 3, 4, 2, 6, 0])
# Use argpartition to get indices of k largest elements= 
indices = np.argpartition(arr, -3)[-3:]
print(indices)

# Sort the selected indices by their corresponding values in descending order
# indices_sorted = indices[np.argsort(arr[indices])[::-1]]
# print(indices_sorted) 

[3 5 0]


In [24]:
import numpy as np

centroids = np.random.random((256, 70))
q = np.random.random(70)
print(q.shape)


dot_product = centroids @ q.T # (K, D) * (D, 1) -> (K, 1)
# print(dot_product.shape)
norm_vec1 = np.linalg.norm(centroids, axis=1) # (K, 1)
# print(norm_vec1.shape)
norm_vec2 = np.linalg.norm(q)
# print(norm_vec2.shape)

norm = norm_vec1 * norm_vec2
# print(norm.shape)

# # norm = norm.reshape((-1,1))


distances = dot_product / norm
# print(distances.shape)
# distances = distances.flatten()

nearest_clusters = np.argsort(distances)[-5:]
print(nearest_clusters)

(70,)
[ 84 149 224 186  67]


In [3]:
import os
os.chmod('out/clusters/',0o700)